syntax = "proto3";

package agent;

import "common.proto";

service AgentService {
  rpc GetAgent(GetAgentRequest) returns (AgentResponse);
  rpc DeleteAgent(DeleteAgentRequest) returns (DeleteAgentResponse);
  rpc ListAgents(ListAgentsRequest) returns (ListAgentsResponse);
}

message AgentResponse {
  string agent_id = 1;
  string hostname = 2;
  string status = 3;
  string last_seen_at = 4;
  string created_at = 5;
  string updated_at = 6;
}

message GetAgentRequest {
  string agent_id = 1;
}

message DeleteAgentRequest {
  string agent_id = 1;
}

message DeleteAgentResponse {}

message ListAgentsRequest {
  optional common.PaginationRequest pagination = 1;
}

message ListAgentsResponse {
  repeated AgentResponse agents = 1;
  common.PaginationMetadata pagination = 2;
}
