syntax = "proto3";

package job;

enum Status {
  PENDING = 0;
  RUNNING = 1;
  COMPLETED = 2;
  FAILED = 3;
}

message CreateJobRequest {
  string pipeline_id = 1; // UUID of the pipeline to execute
}

message CreateJobResponse {
  string job_id = 1; // UUID of the job created
}

service JobService {
  rpc CreateJob (CreateJobRequest) returns (CreateJobResponse);
  //rpc GetJob (GetJobRequest) returns (JobResponse);
  //rpc ListJobs (ListJobsRequest) returns (ListJobsResponse);
  //rpc UpdateJob (UpdateJobRequest) returns (JobResponse);
  //rpc DeleteJob (DeleteJobRequest) returns (DeleteJobResponse);
}