syntax = "proto3";

package orchestrator;

message WorkerHello {}

message WorkerRegistration {
  string id = 1; // UUID assigned by server
}

message Job {
  string id = 1; // Job UUID
  string pipeline = 2; // pipeline in toml format
}

message Ack {}

message StepResult {
  string step_id = 1;
  int32 status_code = 2;
  string stdout = 3;
  string stderr = 4;
}

service Orchestrator {
  // Worker registers and receives its UUID
  rpc RegisterWorker(WorkerHello) returns (WorkerRegistration);

  // Then server can send a stream of jobs
  rpc Assign(WorkerRegistration) returns (stream Job);

  rpc Report(StepResult) returns (Ack);
}