syntax = "proto3";

package pipeline;

import "common.proto";
import "pipeline_def.proto";

service Pipeline {
  // Create a pipeline
  rpc CreatePipeline(CreatePipelineRequest) returns (PipelineResponse);

  // Get a pipeline by ID
  rpc GetPipeline(GetPipelineRequest) returns (PipelineResponse);

  // Update a pipeline
  rpc UpdatePipeline(UpdatePipelineRequest) returns (PipelineResponse);

  // Delete a pipeline
  rpc DeletePipeline(DeletePipelineRequest) returns (DeletePipelineResponse);

  // List all pipelines
  rpc ListPipelines(ListPipelinesRequest) returns (ListPipelinesResponse);
}

message CreatePipelineRequest { pipeline_def.PipelineContent content = 1; }

message GetPipelineRequest { string pipeline_id = 1; }

message UpdatePipelineRequest {
  string pipeline_id = 1;
  pipeline_def.PipelineContent content = 2;
}

message PipelineResponse {
  string pipeline_id = 1;
  pipeline_def.PipelineContent content = 2;
  string created_at = 3;
  string updated_at = 4;
}

message DeletePipelineRequest { string pipeline_id = 1; }

message DeletePipelineResponse {}

message ListPipelinesRequest {
  optional common.PaginationRequest pagination = 1;
}

message ListPipelinesResponse {
  repeated PipelineResponse pipelines = 1;
  common.PaginationMetadata pagination = 2;
}
