syntax = "proto3";

package pipeline.snapshot;

message CreatePipelineSnapshotRequest {
  string pipeline_id = 1;
}

message CreatePipelineSnapshotResponse {
  string snapshot_id = 1;
}

message GetPipelineSnapshotRequest {
  string snapshot_id = 1;
}

message ListPipelineSnapshotRequest {
  string pipeline_id = 1;
}

message DeletePipelineSnapshotRequest {
  string snapshot_id = 1;
}

message DeletePipelineSnapshotResponse {}

message PipelineSnapshotRecord {
  string snapshot_id = 1;
  string pipeline_id = 2;
  string content = 3;
  string created_at = 4;
}

message ListPipelineSnapshotResponse {
  repeated PipelineSnapshotRecord records = 1;
}

service PipelineSnapshot {
  rpc CreatePipelineSnapshot(CreatePipelineSnapshotRequest) returns (CreatePipelineSnapshotResponse);
  rpc GetPipelineSnapshot(GetPipelineSnapshotRequest) returns (PipelineSnapshotRecord);
  rpc DeletePipelineSnapshot(DeletePipelineSnapshotRequest) returns (DeletePipelineSnapshotResponse);
  rpc ListPipelineSnapshots(ListPipelineSnapshotRequest) returns (ListPipelineSnapshotResponse);
}